return {
    'sphamba/smear-cursor.nvim',
    opts = {
        cursor_color = '#CE857A',
        legacy_computing_symbols_support = true,
        stiffness = 0.13,
        trailing_stiffness = 0.24,
        damping = 0.35,
	    smear_between_buffers = false,
	    legacy_computing_symbols_support_vertical_bars = true,
	    transparent_bg_fallback_color = '#30A030',
	    time_interval = 12,
	    stiffness = 0.35,
	    trailing_stiffness = 0.16,
	    vertical_bar_cursor_insert_mode = true,
	    vertial_bar_cursor = false,
	    anticipation = 0.60,
	    damping = 0.72,
	    trailing_exponent = 1,
	    stiffness_insert_mode = 0.875,
	    trailing_stiffness_insert_mode = 0.175,
	    damping_insert_mode = 0.95,
	    distance_stop_animating_vertical_bar = 0.1,
	    max_shade_no_matrix = 0.95,
	    gamma = 1.82,
  },
}
